from bitbucket import BitBucketRequestParser
from github import GitHubRequestParser
from gitlab import GitLabRequestParser
from gitlabci import GitLabCIRequestParser
from generic import GenericRequestParser
from coding import CodingRequestParser